# Generated by Django 4.0.1 on 2022-01-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_column',
        ),
    ]
