# Generated by Django 4.0.1 on 2022-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash_app', '0002_delete_table_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.TextField()),
                ('table_name', models.TextField()),
                ('column_lst', models.TextField()),
            ],
        ),
    ]
