# Generated by Django 4.0.1 on 2022-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0004_graph_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_attributes',
            name='plot',
            field=models.TextField(default=''),
        ),
    ]
