# Generated by Django 4.0.1 on 2022-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0005_graph_attributes_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_attributes',
            name='plot_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='graph_attributes',
            name='plot',
            field=models.TextField(),
        ),
    ]
