# Generated by Django 4.0.1 on 2022-01-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0006_graph_attributes_plot_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_attributes',
            name='plot_type',
            field=models.TextField(),
        ),
    ]
