# Generated by Django 4.0.1 on 2022-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0007_alter_graph_attributes_plot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.TextField()),
                ('table_name', models.TextField()),
                ('column_name', models.TextField()),
                ('max', models.IntegerField()),
                ('min', models.TextField()),
            ],
        ),
    ]
