# Generated by Django 4.0.1 on 2022-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0010_alarm_attributes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm_attributes',
            name='outlier',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
