# Generated by Django 4.0.1 on 2022-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0011_alarm_attributes_outlier'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_xaxis_schema', models.TextField()),
                ('new_yaxis_schema', models.TextField()),
                ('new_xaxis_table', models.TextField()),
                ('new_yaxis_table', models.TextField()),
                ('new_xaxis_column', models.TextField()),
                ('new_yaxis_column', models.TextField()),
                ('new_plot_type', models.TextField()),
                ('new_plot', models.TextField()),
                ('new_chart_title', models.TextField()),
                ('new_font_color', models.TextField()),
                ('new_font_style', models.TextField()),
                ('new_font_size', models.TextField()),
            ],
        ),
    ]
